services:
  - type: web
    name: lens-ed-fullstack
    env: node
    plan: free
    rootDir: server
    buildCommand: npm install && cd ../client && npm install && npm run build && cp -r ../client/dist/* ./public/
    startCommand: node server.js
    envVars:
      - key: DB_HOST
        value: bhfzwen55qtewehcbzlp-mysql.services.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_NAME
        value: bhfzwen55qtewehcbzlp
      - key: DB_USERNAME
        value: ucpq0la133apiyu5
      - key: DB_PASSWORD
        value: 94ladOWF4aWB1ekXvFJH
      - key: DB_DIALECT
        value: mysql
      - key: JWT_SECRET
        value: your_super_secret_jwt_key_here