services:
  - type: web
    name: lens-ed-backend
    env: node
    plan: free
    buildCommand: npm install && cd ../client && npm install && npm run build && cp -r ../client/dist/* ./public/
    startCommand: node server.js
    rootDir: server
    envVars:
      - key: DB_HOST
        value: your-db-host.clever-cloud.com
      - key: DB_PORT
        value: 3306
      - key: DB_USERNAME
        value: your-db-username
      - key: DB_PASSWORD
        value: your-db-password
      - key: DB_NAME
        value: your-db-name
      - key: DB_DIALECT
        value: mysql
      - key: JWT_SECRET
        value: your_jwt_secret

  - type: static
    name: lens-ed-frontend
    rootDir: client
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://lens-ed-backend.onrender.com